name: build-test-deploy
on: push
jobs:
 build:
    runs-on:ubuntu-latest
    steps:
     - name: checkout the repo code
       uses: actions/checkout@v3
     - run: |
       echo " $(cat hello_world.txt)"
     - name: node setup
      uses: actions/setup-node@4.0.2
      with:
        node-version: '14.x'
     - run: npm install
     - run: npm run build
 test:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: check the repo
       uses: actions/checkout@v3
     - run: echo "$(cat hello_world.txt)"
     - name: node test
       uses: actions/setup-node@4.0.2
       with:
         node-version: '14.x'
     - run: npm install
     - run: npm test
 
